# Generated by Django 5.0.6 on 2024-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=150)),
                ('address_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
